# Generated by Django 3.2.8 on 2021-11-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='clinton@gmail.com', max_length=254),
        ),
    ]
