# Generated by Django 3.2.8 on 2021-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0009_alter_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower_count', models.IntegerField(default=0)),
                ('profile', models.ManyToManyField(to='writer.Profile')),
            ],
        ),
    ]
